import Head from "next/head";

export default function About() {
	return (
		<>
			<Head>
				<title>CpeProg • About</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="w-full flex items-center justify-center min-h-screen">
				<div id="About">
					<h1>about</h1>
				</div>
			</main>
		</>
	);
}
