import { Layout } from "@/components/Layout";
import Head from "next/head";

export default function About() {
	return (
		<>
			<Head>
				<title>CpeProg • About</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="w-full min-h-screen">
				<Layout>Hello</Layout>
			</main>
		</>
	);
}
