import { Layout } from "@/Layouts/About";
import Head from "next/head";

export default function AboutMe() {
	return (
		<>
			<Head>
				<title>CpeProg • About</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="">
				<Layout></Layout>
			</main>
		</>
	);
}
