import Head from "next/head";

export default function Contact() {
	return (
		<>
			<Head>
				<title>CpeProg • Contact</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="">Contact</main>
		</>
	);
}
