import { Layout } from "@/components/Layout";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Home Page</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="flex items-center w-full min-h-screen">
				<Layout>
					<h1>Home</h1>
				</Layout>
			</main>
		</>
	);
}
