/* eslint-disable react/no-unescaped-entities */
/* eslint-disable jsx-a11y/alt-text */
import ProfileImage from "@/assets/images/profile/MyProfile-2.png";
import { Layout } from "@/components/Layout";
import { motion } from "framer-motion";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<>
			<Head>
				<title>CpeProg • Home</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="flex items-center text-textDark w-full min-h-screen">
				<Layout className="pt-0">
					<div className="flex items-center justify-around w-full">
						<div className="">
							<h2 className="text-md cursor-default p-2 rounded-md mb-5 text-bgLight bg-textDark hoverBg">
								👋 Hi! I'm Grian Gajila
							</h2>
							<div>
								<h1 className="text-3xl text-bgDark font-extrabold mb-5">
									Front End <br /> Web / Software Engineer
								</h1>
								<p className="font">
									turning ideas into real life projects.
									<br /> aspiring full stack Web Developer / Software Engineer
								</p>
							</div>
						</div>
						<motion.div whileHover={{ y: -6 }}>
							<div className="  rounded-md bg-gradient-to-tl from-textDark via-bgLight to-textDark via-50% shadow-2xl background-animate">
								<Image src={ProfileImage} alt="Profile.img" className="w-64" />
							</div>
						</motion.div>
					</div>
				</Layout>
			</main>
		</>
	);
}
