/* eslint-disable jsx-a11y/alt-text */
import ProfileImage from "@/assets/images/profile/MyProfile-2.png";
import { Layout } from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<>
			<Head>
				<title>CpeProg • Home</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="flex items-center text-textDark w-full min-h-screen">
				<Layout className="pt-0">
					<div className="flex items-center justify-between w-full">
						<div>
							<Image src={ProfileImage} alt="Profile.img" className="w-96" />
						</div>
					</div>
				</Layout>
			</main>
		</>
	);
}
