import Head from "next/head";

export default function index() {
	return (
		<>
			<Head>
				<title> CpeProg</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="w-full flex items-center justify-center min-h-screen">
				<div id="Projects">Projects</div>
			</main>
		</>
	);
}
