import Head from "next/head";

export default function Projects() {
	return (
		<>
			<Head>
				<title> CpeProg • Projects</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="">Projects</main>
		</>
	);
}
