import Head from "next/head";

export default function Skills() {
	return (
		<>
			<Head>
				<title>Skills</title>
				<meta name="desctiption" content="Generated By Create Next App" />
			</Head>
			<main className="">Skills</main>
		</>
	);
}
